HEURISTIC_RULES = [
    {
        "rule_id": "powershell-encoded-command",
        "attack_id": "T1059.001",
        "behavior": "Encoded PowerShell execution",
        "severity": "high",
        "confidence": "high",
        "score": 1.0,
        "match_any": [
            r"\bpowershell(\.exe)?\b.{0,120}\s-(enc|encodedcommand)\b",
            r"\bpwsh(\.exe)?\b.{0,120}\s-(enc|encodedcommand)\b",
            r"\bfrombase64string\b",
            r"\biex\b.{0,100}\bnew-object\s+net\.webclient\b",
        ],
        "not_patterns": [
            r"heuristic_rules",
            r"attack_id",
            r"behavior\":",
            r"rule_id",
        ],
    },
    {
        "rule_id": "powershell-suspicious-flags",
        "attack_id": "T1059.001",
        "behavior": "Suspicious PowerShell invocation",
        "severity": "high",
        "confidence": "medium",
        "score": 0.8,
        "match_any": [
            r"\bpowershell(\.exe)?\b.{0,140}\s(-nop|-noni|-w hidden|-windowstyle\s+hidden|-ep\s+bypass|-executionpolicy\s+bypass)\b",
            r"\bpwsh(\.exe)?\b.{0,140}\s(-nop|-noni|-w hidden|-windowstyle\s+hidden)\b",
        ],
        "not_patterns": [
            r"heuristic_rules",
            r"attack_id",
            r"behavior\":",
        ],
    },
    {
        "rule_id": "cmd-shell",
        "attack_id": "T1059.003",
        "behavior": "Command shell execution",
        "severity": "medium",
        "confidence": "medium",
        "score": 0.65,
        "match_any": [
            r"\bcmd(\.exe)?\s+/[cr]\b",
        ],
        "not_patterns": [
            r"heuristic_rules",
            r"attack_id",
        ],
    },
    {
        "rule_id": "scheduled-task-create",
        "attack_id": "T1053.005",
        "behavior": "Scheduled task creation or update",
        "severity": "high",
        "confidence": "high",
        "score": 0.95,
        "match_any": [
            r"\bschtasks(\.exe)?\b.{0,100}/create\b",
            r"\bschtasks(\.exe)?\b.{0,100}/change\b",
        ],
    },
    {
        "rule_id": "service-creation",
        "attack_id": "T1543.003",
        "behavior": "Windows service creation",
        "severity": "high",
        "confidence": "high",
        "score": 0.9,
        "match_any": [
            r"\bsc(\.exe)?\b.{0,80}\bcreate\b",
            r"\bnew-service\b",
            r"\bcreateservicew?\b",
        ],
        "not_patterns": [
            r"heuristic_rules",
            r"attack_id",
        ],
    },
    {
        "rule_id": "rundll32-execution",
        "attack_id": "T1218.011",
        "behavior": "Rundll32 proxy execution",
        "severity": "high",
        "confidence": "medium",
        "score": 0.75,
        "match_any": [
            r"\brundll32(\.exe)?\b",
        ],
        "context_any": [
            r"\.dll\b",
            r"javascript:",
            r"mshtml",
            r"#\d+\b",
        ],
        "not_patterns": [
            r"rule_id",
            r"behavior\":",
        ],
    },
    {
        "rule_id": "regsvr32-execution",
        "attack_id": "T1218.010",
        "behavior": "Regsvr32 proxy execution",
        "severity": "high",
        "confidence": "medium",
        "score": 0.75,
        "match_any": [
            r"\bregsvr32(\.exe)?\b",
        ],
        "context_any": [
            r"\s/i\b",
            r"\s/s\b",
            r"https?://",
            r"\.sct\b",
            r"\.dll\b",
        ],
        "not_patterns": [
            r"rule_id",
            r"behavior\":",
        ],
    },
    {
        "rule_id": "certutil-transfer",
        "attack_id": "T1105",
        "behavior": "Ingress tool transfer via certutil",
        "severity": "high",
        "confidence": "high",
        "score": 0.9,
        "match_any": [
            r"\bcertutil(\.exe)?\b.{0,120}(-urlcache|-decode|-decodehex|-verifyctl)\b",
        ],
    },
    {
        "rule_id": "bits-job",
        "attack_id": "T1197",
        "behavior": "BITS job usage",
        "severity": "medium",
        "confidence": "medium",
        "score": 0.7,
        "match_any": [
            r"\bbitsadmin(\.exe)?\b",
            r"\bstart-bits?transfer\b",
        ],
    },
    {
        "rule_id": "lsass-minidump",
        "attack_id": "T1003.001",
        "behavior": "LSASS dump or credential extraction activity",
        "severity": "high",
        "confidence": "high",
        "score": 1.0,
        "match_any": [
            r"\bmimikatz\b",
            r"\bsekurlsa::",
            r"\bprocdump(\.exe)?\b.{0,120}\blsass(\.exe)?\b",
            r"\brundll32(\.exe)?\b.{0,140}\bcomsvcs\.dll\b.{0,80}\bminidump\b",
            r"\bwerfault(\.exe)?\b.{0,120}\blsass(\.exe)?\b",
        ],
        "not_patterns": [
            r"heuristic_rules",
            r"behavior\":",
        ],
    },
    {
        "rule_id": "account-discovery",
        "attack_id": "T1087",
        "behavior": "Account discovery",
        "severity": "low",
        "confidence": "medium",
        "score": 0.45,
        "match_any": [
            r"\bnet(\.exe)?\s+user\b",
            r"\bwhoami(\.exe)?\b",
            r"\bquery\s+user\b",
        ],
    },
    {
        "rule_id": "system-discovery",
        "attack_id": "T1082",
        "behavior": "System information discovery",
        "severity": "low",
        "confidence": "medium",
        "score": 0.4,
        "match_any": [
            r"\bsysteminfo\b",
            r"\bhostname\b",
            r"\bwmic(\.exe)?\s+os\b",
        ],
    },
    {
        "rule_id": "network-discovery",
        "attack_id": "T1016",
        "behavior": "System network configuration discovery",
        "severity": "low",
        "confidence": "medium",
        "score": 0.4,
        "match_any": [
            r"\bipconfig\b",
            r"\broute\s+print\b",
            r"\bnetstat\b",
        ],
    },
    {
        "rule_id": "remote-service-usage",
        "attack_id": "T1021",
        "behavior": "Remote service activity",
        "severity": "medium",
        "confidence": "medium",
        "score": 0.65,
        "match_any": [
            r"\bpsexec\b",
            r"\bwinrm\b",
            r"\bwmic(\.exe)?\b.{0,80}\b/node:\b",
            r"\bwmiprvse(\.exe)?\b",
        ],
    },
]
